// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC--JM4xQZNNe8vr-5zfNQZz-NtLGB0Eo',
    appId: '1:1028737417039:web:5b664d620589c795178f3a',
    messagingSenderId: '1028737417039',
    projectId: 'sync-study-92005',
    authDomain: 'sync-study-92005.firebaseapp.com',
    storageBucket: 'sync-study-92005.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMCnste5t59xU8Hs-QLH1aamw10VDohmE',
    appId: '1:1028737417039:android:e719b4a925d72f4b178f3a',
    messagingSenderId: '1028737417039',
    projectId: 'sync-study-92005',
    storageBucket: 'sync-study-92005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHQCKjWXr5UhJPJHUvFjBGZEf751-PSo',
    appId: '1:1028737417039:ios:c75fba04f73db7ed178f3a',
    messagingSenderId: '1028737417039',
    projectId: 'sync-study-92005',
    storageBucket: 'sync-study-92005.firebasestorage.app',
    iosBundleId: 'com.studyGroup.studyGroupFrontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdHQCKjWXr5UhJPJHUvFjBGZEf751-PSo',
    appId: '1:1028737417039:ios:c75fba04f73db7ed178f3a',
    messagingSenderId: '1028737417039',
    projectId: 'sync-study-92005',
    storageBucket: 'sync-study-92005.firebasestorage.app',
    iosBundleId: 'com.studyGroup.studyGroupFrontEnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC--JM4xQZNNe8vr-5zfNQZz-NtLGB0Eo',
    appId: '1:1028737417039:web:eb40117d167caf46178f3a',
    messagingSenderId: '1028737417039',
    projectId: 'sync-study-92005',
    authDomain: 'sync-study-92005.firebaseapp.com',
    storageBucket: 'sync-study-92005.firebasestorage.app',
  );
}
